### ISSUE TITLE
Cannot read property 'getCurrentUser' of undefined

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/angular-eha.couchdb-auth#19]
Hi i am updating the Sense dashboard in order to use this service, but i get an error when serving my app locally, where it is not minified. I get this error in console while the app is bootstrapping:
```
TypeError: Cannot read property 'getCurrentUser' of undefined
    at ehaCouchDbAuthService.ngModule.provider.requireAuthenticatedUser (couchdb-auth.js:287)
    at auth (routes.js:6)
```
[This is the part of my code](https://github.com/danse/sense-dashboard/blob/117/app/scripts/configuration/routes.js#L6) which is calling the auth provider, and [this is the line in the auth module which raises the exception](https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/067010abd8595a616ccaa04c037100f8f2aabcd9/src/auth.service.js#L287). Inspecting it with the debugger, it seems that both `ehaCouchDbAuthService` and `$q` are undefined there, like if the dependency injection did not work.

I am using the not minified version of the module, linked via Wiredep. Also the minified version leads to the same error.

I am not sure how the dependencies should get injected there, maybe it is a new Angular feature? Or maybe i should have some Grunt task running on the dist files? I am using Angular `1.3.18`

**Comment by tthew** [comment]
@danse what happens if you call the provider like this?

```
      .when('/cases', {
        templateUrl: 'views/cases.html',
        controller: 'CasesCtrl',
        resolve: ehaCouchDbAuthServiceProvider.requireAuthenticatedUser
      })
```

**Comment by tthew** [comment]
or even;

```
      .when('/cases', {
        templateUrl: 'views/cases.html',
        controller: 'CasesCtrl',
        resolve: {
           auth: ehaCouchDbAuthServiceProvider.requireAuthenticatedUser
        }
      })
```

**Comment by tthew** [comment]
I _think_ the issue _may_ be stemming from wrapping the provider call in another (injected) function.

**Comment by danse** [comment]
aha, you are right! `when` will inject the value of `resolve`, so i need to pass the function directly. [This works](https://github.com/danse/sense-dashboard/blob/117/app/scripts/configuration/routes.js#L5), i will extend the doc

**Comment by tthew** [comment]
:+1:
