### ISSUE TITLE
Can this module be used in interceptors?

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/angular-eha.couchdb-auth#21]
I tried to use the module in an `$http` interceptor, in order to log out the user upon an auth error. I added `ehaCouchDbAuthService` in the interceptor in order to call its `signOut` method, but i stumbled upon a circular dependency:
```
Uncaught Error: [$injector:cdep] Circular dependency found: $http <- Restangular <- ehaCouchDbAuthService <- authInterceptor <- $http <- gettextCatalog
```
I wonder how you did this in other projects. How to log out the user when a token expires?

**Comment by danse** [comment]
@tthew, you are probably the only person around who can give me some hints!

**Comment by tthew** [comment]
Apologies the docs around this are pretty poor.  The module provides it's own interceptor;

https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/master/src/http-interceptor.js

It takes care of applying the bearer token header to the outgoing requests (you need to configure which hosts you want to intercept requests for) as well as intercepting error responses and triggering events 
that your app can respond to.

The service provides an `.on` method and triggers one of two events `unauthorized` and `unauthenticated`, see [readme](https://github.com/eHealthAfrica/angular-eha.couchdb-auth#onevent-handler) for info (authenticationStateChange was removed, docs need updating there).

**Comment by danse** [comment]
Cool, well this is an opportunity to improve the doc. I will issue a couple of pull requests
