### ISSUE TITLE
Cookie auth not working with PouchDB

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/angular-eha.couchdb-auth#48]
I'm trying to integrate angular-eha.couchdb-auth with PouchDB's http adaptor (not using localstorage) and stock CouchDB.

The call to `_session` responds fine (including the HttpOnly cookie), but future requests (initiated by PouchDB) are always 401s, which suggests cookie auth is not working; inspecting the requests shows the cookie is not being sent.

Live [reduced test case](http://bl.ocks.org/tlvince/b4214358a84272bd46df).

**Comment by tlvince** [comment]
@tthew would you mind taking a look?

**Comment by tthew** [comment]
Indeed cookie auth never got implemented.  It was an oversight as we never used it in that context.  Not sure if / when I will get an opportunity to look at this.

**Comment by tlvince** [comment]
What exactly needs to be implemented? As far as I'm aware, so long as CouchDB has cookie auth enabled, it'll respond with `Set-Cookie:AuthSession=xxx; ...; HttpOnly`, which'll be handled by the browser accordingly. [pouchdb-authentication#login](https://github.com/nolanlawson/pouchdb-authentication/blob/9cc470139ec7e3dd73e1cef5394ce00c9f344494/dist/pouchdb.authentication.js#L67-L89) doesn't seem to do anything special in this regard.

**Comment by tthew** [comment]
You're right; CouchDB will return a cookie and the browser will do it's thing.  I'm afraid I've no experience with pouchdb's http adaptor, nor pouchdb-authentication, and this module has never been tested (or used) with pouchdb so far as I know.  So you probably know a lot more about this stuff than me. 

Sorry I'm not much help.

**Comment by tlvince** [comment]
I've dropped in `$http` over Restangular on the `signIn` call and it's working as expected. Any :-1:s against a PR that drops Restangular? I assume its currently being used just for convenience?

**Comment by tlvince** [comment]
OK, scrap that. Passing in `withCredentials: true` (which pouchdb-authentiction [sets by default](https://github.com/nolanlawson/pouchdb-authentication/blob/dd3f5731e7fbc48060f0616142afd39515dcfd20/dist/pouchdb.authentication.js#L1369)) fixes this.

Example `config` block:

```js
.config(function(ehaCouchDbAuthServiceProvider) {
  ehaCouchDbAuthServiceProvider.config({
    url: 'https://example.com',
    defaultHttpFields: {
      withCredentials: true
    }
  })
})
```

I think all that immediately needs doing is to document `defaultHttpFields` (#49), although removing Restangular might still be worth doing to remove another moving part/dependency (#50).

**Comment by tthew** [comment]
:+1: lgtm. all for dropping restangular too. In hindsight it was a mistake to use it in this module.
